apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-eks
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: capi-eks-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: capi-eks
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: capi-eks
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-control-plane
  namespace: default
spec:
  network:
    vpc:
      id: vpc-00626aca87820438a
    subnets:
      - id: subnet-03ab5be45da8e7cb2
      - id: subnet-0e94caaaaa25fba3e
      - id: subnet-0d0c61e75cc1f1c08
  addons:
  - conflictResolution: overwrite
    name: vpc-cni
    version: v1.7.5-eksbuild.1
  region: us-west-2
  sshKeyName: capi-eks
  endpointAccess:
    public: false
    private: true
  version: v1.28.0
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: capi-eks-pool-0
  namespace: default
spec:
  clusterName: capi-eks
  replicas: 0
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: capi-eks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: capi-eks-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: capi-eks-pool-0
  namespace: default
spec: {}
