apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-eks
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: capi-eks-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: capi-eks
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: capi-eks
  namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-control-plane
  namespace: default
spec:
  network:
    vpc:
      id: ${VPC_ID}
    subnets: []
  region: us-west-2
  sshKeyName: capi-eks
  roleName: eks-controlplane.cluster-api-provider-aws.sigs.k8s.io
  endpointAccess:
    public: true
    private: true
  addons:
  - conflictResolution: overwrite
    name: vpc-cni
    version: v1.15.3-eksbuild.1
  additionalTags:
    "adsk:moniker": plangrid-C-uw2
  version: v1.28.0
---
kind: Secret
apiVersion: v1
type: Opaque
data:
  value: IyEvYmluL2Jhc2ggLXhlCi9ldGMvZWtzL2Jvb3RzdHJhcC5zaCBkZWZhdWx0XyR7Q0xVU1RFUl9OQU1FfS1jb250cm9sLXBsYW5lCg==
metadata:
  name: capi-eks-bootstrap
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: capi-eks-pool-0
  namespace: default
spec:
  clusterName: capi-eks
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: "capi-eks-bootstrap"
      clusterName: capi-eks
      version: v1.28.0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachinePool
        name: capi-eks-launch-template-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachinePool
metadata:
  name: capi-eks-launch-template-0
spec:
  minSize: 2
  maxSize: 10
  awsLaunchTemplate:
    iamInstanceProfile: eks-worker-node-custom
    instanceType: t3.medium
    sshKeyName: capi-eks
