apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: ${CLUSTER_NAME}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  network:
    vpc:
      id: vpc-00626aca87820438a
    subnets:
      - id: subnet-03ab5be45da8e7cb2
      - id: subnet-0e94caaaaa25fba3e
      - id: subnet-0d0c61e75cc1f1c08
  region: us-west-2
  sshKeyName: ${CLUSTER_NAME}
  roleName: eks-controlplane.cluster-api-provider-aws.sigs.k8s.io
  endpointAccess:
    public: true
    private: true
  addons:
  - conflictResolution: overwrite
    name: vpc-cni
    version: v1.15.3-eksbuild.1
  additionalTags:
    "adsk:moniker": plangrid-C-uw2
  version: v1.28.0
---
kind: Secret
apiVersion: v1
type: Opaque
data:
  value: IyEvYmluL2Jhc2ggLXhlCi9ldGMvZWtzL2Jvb3RzdHJhcC5zaCBkZWZhdWx0XyR7Q0xVU1RFUl9OQU1FfS1jb250cm9sLXBsYW5lCg==
metadata:
  name: ${CLUSTER_NAME}-bootstrap
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ${CLUSTER_NAME}-pool-0
  namespace: default
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: "${CLUSTER_NAME}-bootstrap"
      clusterName: ${CLUSTER_NAME}
      version: v1.28.0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachinePool
        name: ${CLUSTER_NAME}-launch-template-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachinePool
metadata:
  name: ${CLUSTER_NAME}-launch-template-0
spec:
  minSize: 2
  maxSize: 10
  awsLaunchTemplate:
    iamInstanceProfile: eks-worker-node-custom
    instanceType: t3.medium
    sshKeyName: ${CLUSTER_NAME}
