apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: eks-mangement
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'clusters/management/'
    repoURL: https://github.com/rohitasva/eks-ec2-clusterapi-gitops
    targetRevision: HEAD
    #helm:
     # valueFiles:
       # - values-c1.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
