apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: us-west-2-management
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: 'clusters/aws-eks/overlays/us-west-2-management'
    repoURL: https://github.com/rohitasva/eks-clusterapi-argo
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
